apiVersion: apps/v1
kind: Deployment
metadata:
  name: actual-budget
  namespace: actualbudget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actual-budget
  template:
    metadata:
      labels:
        app: actual-budget
    spec:
      containers:
        - name: actual-budget
          image: actualbudget/actual-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5006
          volumeMounts:
            - name: data
              mountPath: /data
          livenessProbe:
            tcpSocket:
              port: 5006
            initialDelaySeconds: 10
            periodSeconds: 20
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: actual-budget-nfs-pvc
