apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: koryalbert
  name: koryalbert
  #namespace: koryalbert-dmz
spec:
  selector:
    matchLabels:
      app: koryalbert
  strategy:
    type: RollingUpdate
    rollingUpdate:
     maxUnavailable: 0
     maxSurge: 2
  template:
    metadata:
      labels:
        app: koryalbert
    spec:
      containers:
        - name: koryalbert
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: website-port
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: website-port
            timeoutSeconds: 1
          startupProbe:
            httpGet:
              path: /
              port: website-port
            initialDelaySeconds: 5
            failureThreshold: 30
            periodSeconds: 5
          resources:
            requests:
              cpu: 20m
              memory: 40Mi
            limits:
              cpu: 100m
              memory: 150Mi
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: koryalbert-data
      volumes:
        - name: koryalbert-data
          nfs:
            server: 192.168.2.244
            path: "/mnt/media/files/Websites/koryalbert"
            readOnly: true
